"""add notifications table

Revision ID: 7aacabda9103
Revises: f06228177b1b
Create Date: 2026-08-17 11:37:28.241217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aacabda9103'
down_revision = 'f06228177b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('AuditID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Action', sa.String(length=50), nullable=False),
    sa.Column('RecordType', sa.String(length=50), nullable=False),
    sa.Column('RecordID', sa.Integer(), nullable=False),
    sa.Column('FieldName', sa.String(length=100), nullable=False),
    sa.Column('OldValue', sa.Text(), nullable=True),
    sa.Column('NewValue', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('AuditID')
    )
    op.create_table('notifications',
    sa.Column('NotificationID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Message', sa.Text(), nullable=False),
    sa.Column('IsRead', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('NotificationID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
