"""add asset document fields

Revision ID: 7efdbe43a336
Revises: d1a2c35055d4
Create Date: 2026-08-11 11:03:02.691139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efdbe43a336'
down_revision = 'd1a2c35055d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('InvoiceFile', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('WarrantyFile', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('WarrantyFile')
        batch_op.drop_column('InvoiceFile')

    # ### end Alembic commands ###
