"""add inventory campaign tables

Revision ID: 948e9102d9bc
Revises: 7aacabda9103
Create Date: 2026-08-18 11:15:40.638448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948e9102d9bc'
down_revision = '7aacabda9103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_campaigns',
    sa.Column('CampaignID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LocationID', sa.Integer(), nullable=False),
    sa.Column('CreatedBy', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ClosedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.UserID'], ),
    sa.ForeignKeyConstraint(['LocationID'], ['locations.LocationID'], ),
    sa.PrimaryKeyConstraint('CampaignID')
    )
    op.create_table('inventory_scans',
    sa.Column('ScanID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CampaignID', sa.Integer(), nullable=False),
    sa.Column('AssetID', sa.Integer(), nullable=False),
    sa.Column('ScanStatus', sa.String(length=30), nullable=False),
    sa.Column('ScannedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AssetID'], ['assets.AssetID'], ),
    sa.ForeignKeyConstraint(['CampaignID'], ['inventory_campaigns.CampaignID'], ),
    sa.PrimaryKeyConstraint('ScanID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_scans')
    op.drop_table('inventory_campaigns')
    # ### end Alembic commands ###
