"""add movement model

Revision ID: b66e2ef9fec2
Revises: eae7576ce6a4
Create Date: 2026-08-12 10:46:54.543244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66e2ef9fec2'
down_revision = 'eae7576ce6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements',
    sa.Column('MovementID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AssetID', sa.Integer(), nullable=False),
    sa.Column('AssignmentID', sa.Integer(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('MovementType', sa.String(length=30), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('MovementDate', sa.Date(), nullable=False),
    sa.Column('Note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['AssetID'], ['assets.AssetID'], ),
    sa.ForeignKeyConstraint(['AssignmentID'], ['assignments.AssignmentID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('MovementID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movements')
    # ### end Alembic commands ###
