"""add assignment fields

Revision ID: eae7576ce6a4
Revises: 7efdbe43a336
Create Date: 2026-08-12 09:32:35.728104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae7576ce6a4'
down_revision = '7efdbe43a336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ReturnCondition', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('ReturnCondition')
        batch_op.drop_column('Note')
        batch_op.drop_column('Quantity')

    # ### end Alembic commands ###
