"""add asset and rejection reason to requests

Revision ID: f06228177b1b
Revises: b69390e3707e
Create Date: 2026-08-14 10:52:45.900763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f06228177b1b'
down_revision = 'b69390e3707e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_active_asset_assignment'))
        batch_op.create_index('idx_active_asset_assignment', ['AssetID', 'ReturnedDate'], unique=False)
        batch_op.drop_column('ActiveAssetID')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AssetID', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('RejectionReason', sa.Text(), nullable=True))
        batch_op.alter_column('Status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(None, 'assets', ['AssetID'], ['AssetID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('Status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('RejectionReason')
        batch_op.drop_column('AssetID')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ActiveAssetID', mysql.INTEGER(), sa.Computed('((case when (`ReturnedDate` is null) then `AssetID` else NULL end))', persisted=True), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_active_asset_assignment')
        batch_op.create_index(batch_op.f('uq_active_asset_assignment'), ['ActiveAssetID'], unique=True)

    # ### end Alembic commands ###
